### ISSUE TITLE
Reword justification question

### ISSUE THREAD

**Issue by ethanheppner** [18F/tts-micropurchase-bots#25]
Noticed an uptick in insufficient justifications being submitted via the google from. Can you please modify the question asked to incorporate this sentiment…“What is the attendee’s justification for attending this event, including why their participation adds value to / benefits GSA / TTS?”

**Comment by ethanheppner** [comment]
Explore min character requirement

**Comment by ethanheppner** [comment]
Not part of email to supervisor?

**Comment by keithrwilson** [comment]
What is the attendee's justification for attending this event, including why their participation adds value to and/or benefits GSA/TTS?

EXAMPLE DOC:  https://docs.google.com/document/d/13BCETwANCx9JRPgFbRibqRGthIvf4XQ-WTYD0P30PWg/edit

**Comment by stevenjosephwilliams** [comment]
The google document is ready for review. Note: I have created a generic example that uses the referenced narrative structure to create a "good" justification.
