### ISSUE TITLE
Formally deprecate C2

### ISSUE THREAD

**Issue by ethanheppner** [18F/tts-micropurchase-bots#30]
- [x] Ensure all outstanding logs are have C2 approval and receipts statically documented in the [P-card SSoT](https://docs.google.com/spreadsheets/d/1DZNfdF48bm6ilVWN8E6yK0_FuayAdkp-cZUXfVZf3NM/edit#gid=1246278447).
- [x] @melanieleopold to clarify final status of remaining item from C2 queue.
- [x] Run final report from C2
- [x] Susan to verify if anything else required from GSA IT, any recommended edits to [this checklist](https://before-you-ship.18f.gov/infrastructure/decommissioning/).
- [x] @afeld to get access to cloud.gov app/space/org and then:
  - [x] Set up redirects from cap.18f.gov, requests.18f.gov to new [Micropurchase request form](https://docs.google.com/forms/d/e/1FAIpQLSd-GoOE9xWWfJvdZNRP3SE7mj5ysI_RfM8brxdG8YpyJV9yKA/viewform)
  - [x] Ask cloud-gov-support@gsa.gov for the cloud.gov organization (`gsa-acq-c2`) to be deleted.
  - [x] ~~Delete any associated AWS resources, and decommission any AWS accounts.~~
  - [x] Archive the GitHub repositor(ies).
  - [x] Clean up any DNS entries that are no longer needed, from the DNS repository or elsewhere.
  - [x] ~~If there’s a custom (second-level) domain, figure out what to do with it.~~
- [x] Ethan or Aidan? to do the following:
  - [x] Email GSA Privacy Office at gsa.privacyact@gsa.gov so they can take down the SORN
  - [x] Complete decommit paperwork-- fill out and send the Disposal Notification Template, which can be found in the list of IT Security Forms
  - [x] Archive the Slack channel #cap, #c2-purchase-questions
- [x] Update [P-Card documentation](https://docs.google.com/document/d/1LxkTsQPA4v4ZpJNpJcnSBX07WVxQQwfVtXKx236EfEU/edit#)
- [x] Delete any associated AWS resources, and decommission any AWS accounts. Ask in [#infrastructure](https://gsa-tts.slack.com/messages/infrastructure) for help.
- [x] Remove (sub)accounts in external services
  - [x] New Relic - [#admins-newrelic](https://gsa-tts.slack.com/messages/admins-newrelic)
- [x] Remove any external integrations
  - [x] [Slack](https://handbook.18f.gov/slack/#integrations)

**Comment by afeld** [comment]
More tasks: https://before-you-ship.18f.gov/infrastructure/decommissioning/

**Comment by afeld** [comment]
Let the Tech Portfolio know how we can help!

**Comment by brittag** [comment]
Suggest also coordinating with cloud.gov team in #cg-support when you all are ready to decommission the org!

**Comment by ethanheppner** [comment]
Thanks Aidan and Britta. A few questions about the checklist:

1. Should the cloud.gov org, AWS resources, and DNS entries, be deleted
before or after we put in the notice to decommit C2 with GSA IT?
2. requests.18f.gov and cap.18f.gov are second-level domains, right? Do we
figure out what to do with those before or after decommitting with IT?
3. Also cc-ing Eric on this: does GSA IT help with notifying the privacy
office and filling out the disposal notification template as indicated here
<https://before-you-ship.18f.gov/infrastructure/decommissioning/>?

Ethan Heppner
Program Analyst, TTS Business Operations
https://gsa.gov/tts

**Comment by stvnrlly** [comment]
I think it would make sense to redirect those domains to the new forms for at least a little while, to help guide infrequent users to the right places.

**Comment by ethanheppner** [comment]
Right, that makes sense, thanks Steven.

Britta and Aidan, any thoughts on 1?

Eric, any thoughts on 3?

We are just about ready to shut down and I want to make sure I'm doing
shutdown work in the order that doesn't mess anything up :)

**Comment by afeld** [comment]
Done from the TTS side!
